site_name: suMEDS
site_description: Lazy, privacy-aware code occurrence summaries for MEDS datasets
repo_url: https://github.com/Medical-Event-Data-Standard/meds
repo_name: MEDS standard
strict: true
nav:
  - Overview: index.md
  - Usage: usage.md
  - Configuration: configuration.md
  - Python API: api.md
  - Privacy: privacy.md
  - Development: development.md
theme:
  name: mkdocs
markdown_extensions:
  - admonition
  - attr_list
  - tables
